modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="playerex"
version="0.0.1"
displayName="Player Ex"
displayURL="https://github.com/CleverNucleus/Crucible"
logoFile="logo.png"
credits="CleverNucleus"
authors="CleverNucleus"

description='''
A clever implementaton of a novel attributes system for players.
'''

[[dependencies.playerex]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.playerex]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"