modLoader="javafml"
loaderVersion="[34,)"
license="MIT License"

[[mods]]
modId="playerex"
version="1.1.2"
displayName="Player Ex"
displayURL="https://github.com/CleverNucleus/PlayerEx"
logoFile="logo.png"
credits="CleverNucleus: Code and major texturer; Kyrise, Bonsaiheldin, Joe Williamson, Orteil, 7Soul1 & Darina Matvienko: Awesome textures."
authors="CleverNucleus"

description='''
A clever implementaton of a novel attributes system for players.
'''

[[dependencies.playerex]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.playerex]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"