modLoader="javafml"
loaderVersion="[35,)"
license="MIT License"

[[mods]]
modId="playerex"
version="1.1.7.5"
displayName="Player Ex"
displayURL="https://github.com/CleverNucleus/PlayerEx"
logoFile="logo.png"
credits="CleverNucleus: Code and major texturer; sky_bai: simplified chinese translation (thanks!)"
authors="CleverNucleus"

description='''
A clever implementaton of a novel attributes API for players and devs.
'''

[[dependencies.playerex]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.playerex]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"